### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by jclarkk** [microsoft/TRELLIS#1]
The results look great in the HF demo! Really looking forward to play around with it once the code is available.

Are you planning to release the training code too?

**Comment by JeffreyXiang** [comment]
Hi! Thank you for your interest in our project!  
  
Yes, we will release our training code along with the data, which includes a filtered list, text captions, and the preparation code.  
  
Although we are committed to cleaning and annotating the code, the training and data preparation components might not be ready in the initial release. Please stay tuned!

**Comment by jclarkk** [comment]
Great news! Thanks for the prompt response!

**Comment by peebler** [comment]
This is awesome! Thanks for open-sourcing everything. It's a breath of fresh air compared to the famous work ■■■■ that promised the world but then closed their issues. You rock!
Just one thing: Any idea when the full release of training is coming? A timeline would save me from the daily ritual of checking the repo first thing in the morning.

**Comment by YuDeng** [comment]
> [@JeffreyXiang](https://github.com/JeffreyXiang) This is awesome! Thanks for open-sourcing everything. It's a breath of fresh air compared to the famous work ■■■■ that promised the world but then closed their issues. You rock! Just one thing: Any idea when the full release of training is coming? A timeline would save me from the daily ritual of checking the repo first thing in the morning.

https://github.com/microsoft/TRELLIS/issues/44
