### ISSUE TITLE
objaverse-github download error

### ISSUE THREAD

**Issue by feiqiu-cyber** [microsoft/TRELLIS#100]
![Image](https://github.com/user-attachments/assets/5df4097a-3fd9-4555-bf72-0253cb7e38a3)
Very appreciate for your data opensource, have you met the error when download source github from objaverse-xl? If yes, how to solve it. Or May be  I can ignore the error. Thanks again!

**Comment by JeffreyXiang** [comment]
Could be network issue or the repo does not exist anymore. Ignoring them is ok.

**Comment by feiqiu-cyber** [comment]
> Could be network issue or the repo does not exist anymore. Ignoring them is ok.

OK, Thank you very much
