### ISSUE TITLE
1-Click Installers for Windows, RunPod and Massed Compute including Flash Attention - Purely Python 3.10 venv - took so many hours

### ISSUE THREAD

**Issue by FurkanGozukara** [microsoft/TRELLIS#13]
Thank you so much for this amazing work Microsoft. 

I have been working on making installers for this repository

I achieved to install everything into a Python 3.10 venv 

All you need are : Python 3.10.11, CUDA 12.4, cuDNN 8.9.7, C++ Tools and Git 

Full step-by-step tutorial for above requirements : https://youtu.be/DrhUHnYfwC0

Installers are shared here : [Click to download](https://www.patreon.com/posts/117470976)

Installers are .bat and .sh files so fully editable

Massed Compute installers not working atm will be fixed hopefully tomorrow

RunPod installer works on official runpod/pytorch:2.2.0-py3.10-cuda12.1.1 template

Uses Torch 2.5.1 and CUDA 12.4, Triton and Flash Attention - so maximum performance

It is working blazing fast on RTX 3090 - uses around 14-15 GB VRAM

I will also hopefully make a full video tutorial ASAP. 

Installers uses this repo - requires no admin rights or PowerShell - just bat file 

![Image](https://github.com/user-attachments/assets/8dc4f711-7d8b-4b77-af2f-e89dcc6fa15c)

![Image](https://github.com/user-attachments/assets/39960208-7c91-49bf-87bc-d37d385a415e)

![Image](https://github.com/user-attachments/assets/b5d43629-26ca-4dfd-88ed-8ae3b4a4ebf5)

**Comment by JeffreyXiang** [comment]
Thank you so much for your contribution and effort in adding Windows support! Will add this to the pinned #3 Windows support discussion。

**Comment by Abocg** [comment]
@FurkanGozukara  so ether I have to flow about an hour tutorial to install it or I have to pay for one click installer. I.ve been notice you snice while you tent to complicate things   in order to go and buy your genius one click solution. such a greedy man. the open source community is way generous than your  genius  stuff. your post here nothing but a marketing for your patreon .

**Comment by JeffreyXiang** [comment]
Closed as being no helpful.
