### ISSUE TITLE
Radiance Field used?

### ISSUE THREAD

**Issue by wes-kay** [microsoft/TRELLIS#15]
![Image](https://github.com/user-attachments/assets/eb49dd8d-82c2-402c-81b1-a45e7b9b5df4)

`app.py` doesn't use a radiance field to export but the sample code in the readme is, so I'm a little confused as to what exactly we should be doing and if the export videos in my example are exporting properly. 

```
image = Image.open(file_path)
pipeline = TrellisImageTo3DPipeline.from_pretrained("JeffreyXiang/TRELLIS-image-large")
pipeline.cuda()
outputs = pipeline.run(
    image, 
    seed=1, 
    formats=["gaussian", "radiance_field", "mesh"]
)

if 'gaussian' in outputs and outputs['gaussian']:
    g = render_utils.render_video(outputs['gaussian'][0])
    if 'color' in g:
        p = os.path.join(output_dir, "sample_gs.mp4")
        imageio.mimsave(p, g['color'], fps=30)

if 'radiance_field' in outputs and outputs['radiance_field']:
    r = render_utils.render_video(outputs['radiance_field'][0])
    if 'color' in r:
        p = os.path.join(output_dir, "sample_rf.mp4")
        imageio.mimsave(p, r['color'], fps=30)

if 'mesh' in outputs and outputs['mesh']:
    m = render_utils.render_video(outputs['mesh'][0])
    if 'color' in m:
        p = os.path.join(output_dir, "sample_mesh.mp4")
        imageio.mimsave(p, m['color'], fps=30)
    if 'normal' in m:
        p = os.path.join(output_dir, "sample_mesh_normal.mp4")
        imageio.mimsave(p, m['normal'], fps=30)

if 'gaussian' in outputs and 'mesh' in outputs:
    glb = postprocessing_utils.to_glb(
        outputs['gaussian'][0], 
        outputs['mesh'][0], 
        simplify=0.95, 
        texture_size=1024
    )
    p = os.path.join(output_dir, f"{uuid.uuid4()}.glb")
    glb.export(p)

```

**Comment by JeffreyXiang** [comment]
In this research, we focused on developing a unified latent space for various 3D representations, including but not limited to 3D Gaussians, Radiance Fields, and Meshes. The GLB export functionality is a straightforward extension of our model's capabilities, where the appearance from 3D Gaussians is baked into Meshes.
﻿
If your use case only requires a textured mesh (the GLB file), decoding the Radiance Field is not necessary. However, in example.py, our goal is to showcase the full range of outputs that the model can produce.
﻿
I hope this clears up the confusion. Let us know if you have further questions!

Cool results BTW! The results are correct, the 3D Gassian and Radiance Field video should be very similar.
