### ISSUE TITLE
model release

### ISSUE THREAD

**Issue by NobodyHere2024-hash** [microsoft/TRELLIS#2]
Hello, great job! May I ask if you will open-source the XL model?

**Comment by JeffreyXiang** [comment]
Hi! Thanks for your interest! We have released the inference code and TRELLIS-image-large model. The text-conditioned models, including the XL one, will be released in the future. See [https://github.com/microsoft/TRELLIS#-pretrained-models](https://github.com/microsoft/TRELLIS#-pretrained-models).

**Comment by JeffreyXiang** [comment]
> > Hi! Thanks for your interest! We have released the inference code and TRELLIS-image-large model. The text-conditioned models, including the XL one, will be released in the future. See https://github.com/microsoft/TRELLIS#-pretrained-models.
> 
> Text condition model include the local manipulation of meshes?

Hi!

The text-conditioned models themselves do not support instruct-based editing (i.e. what achieved by EMU-edit). We achieved that through a tuning-free editing algorithm [RePaint](https://github.com/andreas128/RePaint). It operates with the text-conditioned model and a user-specified bounding box. You can refer to section 3.4 of our paper for more details.
