### ISSUE TITLE
ComfyUI custom node

### ISSUE THREAD

**Issue by Uniky** [microsoft/TRELLIS#21]
Try to implement a ComfyUI node for Trellis, the code is adapted from the Gradio version app.py. I got the first step working which generates the video, but when I tried to extract the mesh, I got errors: 
![Image](https://github.com/user-attachments/assets/b694cc9d-2ee5-4817-aa16-9d4bdf56fb49)

Sampling: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.96it/s]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  7.86it/s]
Rendering: 120it [00:00, 134.99it/s]
Rendering: 120it [00:00, 129.66it/s]
state: {'gaussian': {'aabb': [-0.5, -0.5, -0.5, 1.0, 1.0, 1.0], 'sh_degree': 0, 'mininum_kernel_size': 0.0009, 'scaling_bias': 0.004, 'opacity_bias': 0.1, 'scaling_activation': 'softplus', '_xyz': array([[0.17800711, 0.6889143 , 0.37405646],
       [0.17874639, 0.6882722 , 0.3747258 ],
       [0.17835678, 0.68865436, 0.37436348],
       ...,
       [0.77873534, 0.5525637 , 0.4882899 ],
       [0.77751946, 0.54526347, 0.48580328],
       [0.7774067 , 0.548336  , 0.48444998]], dtype=float32), '_features_dc': array([[[-1.5232774 , -1.206336  , -0.6697717 ]],

       [[-1.5769104 , -1.3671327 , -0.98691094]],

       [[-1.1625017 , -0.7061986 , -0.08210322]],

       ...,

       [[ 0.35555837,  0.50588864,  0.53489786]],

       [[-1.3261368 , -1.3428636 , -1.2004334 ]],

       [[-1.4149884 , -1.4448271 , -1.3182142 ]]], dtype=float32), '_scaling': array([[-2.82711172e+00, -5.57157421e+00, -1.36082694e-01],
       [-8.73520911e-01, -3.31007338e+00, -2.65938807e+00],
       [-3.02946615e+00, -1.56505919e+00, -1.05140915e+01],
       ...,
       [-1.00571036e+00, -1.81665078e-01, -1.09666414e+01],
       [-6.43692136e-01, -1.05645475e+01, -6.81989193e-01],
       [ 6.77150488e-03, -1.05288305e+01, -2.76489288e-01]], dtype=float32), '_rotation': array([[-0.5269622 ,  0.13671234,  0.129914  , -0.11830652],
       [-0.66408205, -0.00638912, -0.15057866, -0.17248885],
       [-0.7886389 , -0.07075121, -0.11181974,  0.08366678],
       ...,
       [-0.55127436, -0.13461077,  0.27111244,  0.07928681],
       [-0.79853314,  0.02191008,  0.0099382 ,  0.31350046],
       [-0.59878355, -0.096067  ,  0.03191362, -0.26195556]],
      dtype=float32), '_opacity': array([[0.10551411],
       [0.05506805],
       [0.30922812],
       ...,
       [2.4815016 ],
       [2.84298   ],
       [2.245427  ]], dtype=float32)}, 'mesh': {'vertices': array([[-0.32848486,  0.19255085, -0.13539027],
       [-0.32839948,  0.19215645, -0.13335796],
       [-0.32812524,  0.19148742, -0.1297977 ],
       ...,
       [ 0.27567846,  0.04310427,  0.1113553 ],
       [ 0.28561968,  0.01644675, -0.04380095],
       [ 0.2795277 ,  0.0200796 , -0.04490579]], dtype=float32), 'faces': array([[     0,      1,      4],
       [     4,      1,      5],
       [     1,      2,      5],
       ...,
       [133041, 133203, 133056],
       [133202, 133203, 133200],
       [133202, 133200, 133199]], dtype=int64)}, 'trial_id': '8bd15060-c43e-4bd3-8762-0b3ad0a77a60'}
gs, mesh, trial_id: <trellis.representations.gaussian.gaussian_model.Gaussian object at 0x00000181ACB917E0> {'vertices': tensor([[-0.3285,  0.1926, -0.1354],
        [-0.3284,  0.1922, -0.1334],
        [-0.3281,  0.1915, -0.1298],
        ...,
        [ 0.2757,  0.0431,  0.1114],
        [ 0.2856,  0.0164, -0.0438],
        [ 0.2795,  0.0201, -0.0449]], device='cuda:0'), 'faces': tensor([[     0,      1,      4],
        [     4,      1,      5],
        [     1,      2,      5],
        ...,
        [133041, 133203, 133056],
        [133202, 133203, 133200],
        [133202, 133200, 133199]], device='cuda:0')} 8bd15060-c43e-4bd3-8762-0b3ad0a77a60
INFO- Loaded 4247 vertices and 8478 faces.

100% done
Rendering: 100it [00:01, 80.40it/s]
Error in generate function: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis_node.py", line 166, in generate
    glb = postprocessing_utils.to_glb(
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis\utils\postprocessing_utils.py", line 446, in to_glb
    texture = bake_texture(
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis\utils\postprocessing_utils.py", line 381, in bake_texture
    loss.backward()
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\autograd\__init__.py", line 289, in backward
    _engine_run_backward(
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\autograd\graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

!!! Exception during processing !!! element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "S:\ComfyUI_Win\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\ComfyUI_Win\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\ComfyUI_Win\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\ComfyUI_Win\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis_node.py", line 166, in generate
    glb = postprocessing_utils.to_glb(
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis\utils\postprocessing_utils.py", line 446, in to_glb
    texture = bake_texture(
  File "S:\ComfyUI_Win\ComfyUI\custom_nodes\ComfyUI-Trellis\trellis\utils\postprocessing_utils.py", line 381, in bake_texture
    loss.backward()
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\autograd\__init__.py", line 289, in backward
    _engine_run_backward(
  File "S:\ComfyUI_Win\ComfyUI\venv\lib\site-packages\torch\autograd\graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by ifilipis** [comment]
How did you manage to install it? Which python version are you using? ComfyUI - portable or local? I can't get spconv to install on 3.12. Any version would give me this error 

from cumm.core_cc import tensorview_bind
ImportError: DLL load failed while importing core_cc: The specified module could not be found.

**Comment by ifilipis** [comment]
@planb788 what integrated package? Did it work?

**Comment by Jonasunn** [comment]
Can I try the node? Where can I get it?

**Comment by smthemex** [comment]
![Image](https://github.com/user-attachments/assets/9b25a1a5-3038-4db5-ae9f-acc78c92c0b3)
get error like ：RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn  too
i change a line code ,Although it can run smoothly, it obtains a completely black model.
![Image](https://github.com/user-attachments/assets/e071df66-f567-4934-97b2-dd691732f356)

torch 2.4 .0 python 3.11 
Currently, all successful runs are based on Python 3.10, and the error lies  maybe [here](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/render_utils.py#L107)
observations is a empty tensor list, so mask all false, so get element 0 of tensors does not require grad and does not have a grad_fn

**Comment by selfitisolated** [comment]
> ![Image](https://github.com/user-attachments/assets/9b25a1a5-3038-4db5-ae9f-acc78c92c0b3) get error like ：RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn too i change a line code ,Although it can run smoothly, it obtains a completely black model. ![Image](https://github.com/user-attachments/assets/e071df66-f567-4934-97b2-dd691732f356)
> 
> torch 2.4 .0 python 3.11 Currently, all successful runs are based on Python 3.10, and the error lies maybe [here](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/render_utils.py#L107) observations is a empty tensor list, so mask all false, so get element 0 of tensors does not require grad and does not have a grad_fn

can u share workflow please?

**Comment by psychobee** [comment]
> ![Image](https://github.com/user-attachments/assets/9b25a1a5-3038-4db5-ae9f-acc78c92c0b3) get error like ：RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn too i change a line code ,Although it can run smoothly, it obtains a completely black model. ![Image](https://github.com/user-attachments/assets/e071df66-f567-4934-97b2-dd691732f356)
> 
> torch 2.4 .0 python 3.11 Currently, all successful runs are based on Python 3.10, and the error lies maybe [here](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/render_utils.py#L107) observations is a empty tensor list, so mask all false, so get element 0 of tensors does not require grad and does not have a grad_fn

can you share the code , maybe we can figure out the textures not being intact part please

**Comment by smthemex** [comment]
I didn't solve the problem of not being able to map it, I just added it [ #code](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/postprocessing_utils.py#L381) before the error caused by the empty tensor ，like this：
![Image](https://github.com/user-attachments/assets/fdd79b3a-eeb2-4cf7-96ba-2e53378e0c79)

**Comment by selfitisolated** [comment]
> Correct the previous mistake, the zero loss is not caused by Gaussian, but mostly by nvdiffrast. ![Image](https://github.com/user-attachments/assets/45bfff4a-e793-419d-8ada-8d5af77e1fe2)
> 
> I didn't solve the problem of not being able to map it, I just added it [ #code](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/postprocessing_utils.py#L381) before the error caused by the empty tensor ，like this： ![Image](https://github.com/user-attachments/assets/fdd79b3a-eeb2-4cf7-96ba-2e53378e0c79)

can u please share how u install it in comfyui?

**Comment by smthemex** [comment]
> > Correct the previous mistake, the zero loss is not caused by Gaussian, but mostly by nvdiffrast. ![Image](https://github.com/user-attachments/assets/45bfff4a-e793-419d-8ada-8d5af77e1fe2)
> > I didn't solve the problem of not being able to map it, I just added it [ #code](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/postprocessing_utils.py#L381) before the error caused by the empty tensor ，like this： ![Image](https://github.com/user-attachments/assets/fdd79b3a-eeb2-4cf7-96ba-2e53378e0c79)
> 
> can u please share how u install it in comfyui?

I will release a comfyUI version with detailed installation instructions attached

![Image](https://github.com/user-attachments/assets/56f992cb-8886-4a50-9587-b5d35054e10f)

**Comment by selfitisolated** [comment]
> > > Correct the previous mistake, the zero loss is not caused by Gaussian, but mostly by nvdiffrast. ![Image](https://github.com/user-attachments/assets/45bfff4a-e793-419d-8ada-8d5af77e1fe2)
> > > I didn't solve the problem of not being able to map it, I just added it [ #code](https://github.com/microsoft/TRELLIS/blob/main/trellis/utils/postprocessing_utils.py#L381) before the error caused by the empty tensor ，like this： ![Image](https://github.com/user-attachments/assets/fdd79b3a-eeb2-4cf7-96ba-2e53378e0c79)
> > 
> > 
> > can u please share how u install it in comfyui?
> 
> I will release a [comfyUI version](https://github.com/smthemex/ComfyUI_TRELLIS) with detailed installation instructions attached
> 
> ![Image](https://github.com/user-attachments/assets/56f992cb-8886-4a50-9587-b5d35054e10f)

thank u hero <3

**Comment by JonathanMiroshnik** [comment]
You go king! The moment you get this to work on ComfyUI I already have something set up to port it to Unity in runtime.
