### ISSUE TITLE
NameError: name 'FlexiCubes' is not defined

### ISSUE THREAD

**Issue by moghadas76** [microsoft/TRELLIS#34]
[NameError: name 'FlexiCubes' is not defined](https://github.com/microsoft/TRELLIS/issues/32)

**Comment by dwalter** [comment]
it's part of the submodules:
```bash
git submodule init
git submodule update
```

**Comment by YuDeng** [comment]
Duplicate with https://github.com/microsoft/TRELLIS/issues/32 and https://github.com/microsoft/TRELLIS/issues/4
