### ISSUE TITLE
module 'utils3d' has no attribute 'torch'

### ISSUE THREAD

**Issue by Dan1900** [microsoft/TRELLIS#35]
module 'utils3d' has no attribute 'torch'

**Comment by badarrrr** [comment]
same error,how to solve it?

**Comment by Dan1900** [comment]
pip install git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8

**Comment by badarrrr** [comment]
Thanks! It works!![Image](https://github.com/user-attachments/assets/ccf4eb47-ce35-40f7-97d1-3b648188a914)

**Comment by QDelormeUbi** [comment]
Sorry to revive this topic, but I have the same issue.
I tried the command above, I tried with the commands in the repo for this lib.
I always get 

`Traceback (most recent call last):
  File "/mnt/f/trellis/trellis/TRELLIS/./minimal.py", line 39, in <module>
    video = render_utils.render_video(outputs['gaussian'][0])['color']
  File "/mnt/f/trellis/trellis/TRELLIS/trellis/utils/render_utils.py", line 95, in render_video
    extrinsics, intrinsics = yaw_pitch_r_fov_to_extrinsics_intrinsics(yaws, pitch, r, fov)
  File "/mnt/f/trellis/trellis/TRELLIS/trellis/utils/render_utils.py", line 33, in yaw_pitch_r_fov_to_extrinsics_intrinsics
    extr = utils3d.torch.extrinsics_look_at(orig, torch.tensor([0, 0, 0]).float().cuda(), torch.tensor([0, 0, 1]).float().cuda())
AttributeError: module 'utils3d' has no attribute 'torch'`

I tried to comment out the video generation, but it then fails on the glb post-processing.
I got all the other dependcies but this one.

Is there anything else I could try ?
I'm running a wsl2 ubuntu, Cuda 12.1, torch 2.5.0 if that can help.

It's all the more frustrating that it's the last piece of the script.

**Comment by edwardsmith999** [comment]
There seems to be another package called utils3d 

   https://pypi.org/project/utils3d/

which had no torch. I had to install from

    pip install git+https://github.com/EasternJournalist/utils3d.git#egg=utils3d

which gave 

    Discarding git+https://github.com/EasternJournalist/utils3d.git#egg=utils3d: Requested unknown from git+https://github.com/EasternJournalist/utils3d.git#egg=utils3d has inconsistent name: filename has 'utils3d', but metadata has 'unknown'
    ERROR: Could not find a version that satisfies the requirement utils3d (unavailable) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3)
    ERROR: No matching distribution found for utils3d (unavailable)

until I updated pip

  python3 -m pip install --upgrade pip
