### ISSUE TITLE
How to create multiple-images to 3d ? ( "multiple-image" is photographs taken from various angles of a single photograph )

### ISSUE THREAD

**Issue by ITSTIME1** [microsoft/TRELLIS#36]
I think this model is good, so I wonder how I can create a 3D structure from multiple images. The multiple images are photographs of a single object taken from various angles.

**Comment by YuDeng** [comment]
Hi, the current version of Trellis is for single image to 3D. You can refer to https://github.com/microsoft/TRELLIS/issues/7 for more discussions.

**Comment by YuDeng** [comment]
An experimental multiview image support is updated. See https://github.com/microsoft/TRELLIS?tab=readme-ov-file#-updates.
