### ISSUE TITLE
Gaussiannexport option

### ISSUE THREAD

**Issue by Jhoew** [microsoft/TRELLIS#40]
Do you have recommendations for modifying the web UI to include an 'Export Gaussian' option? I have some transparent objects that look perfect in the MP4 video. It would be great to have the Gaussian option available to experiment with it.

**Comment by wes-kay** [comment]
You can easily add the gaussianne to the `color` in the gradio, or I fully recommend using CLI and modifying the sample in the readme, as I'm finding it's faster to generate as well as gives you more options and ability to batch.

**Comment by 0lento** [comment]
I've done modification for this on my end. I plan on pushing the changes to my fork eventually but I can't tell how long that will take, there's a lot of things in motion here. Simplest way to get the gaussian out is to just do this after you have generated the gaussian with pipeline.run:

gaussian = outputs['gaussian'][0]
gaussian.save_ply("myfilepath.ply")

but do note that this outputs the gaussian that needs to be rotated later. I have rotation code too but I need to see if it can be made simpler.

**Comment by YuDeng** [comment]
We support Gaussian export now. See https://github.com/microsoft/TRELLIS?tab=readme-ov-file#-updates.
