### ISSUE TITLE
feeding trellis impossible shapes as input

### ISSUE THREAD

**Issue by grindhold** [microsoft/TRELLIS#47]
just out of curiosity: have you guys already tried feeding trellis with images of impossible shapes like e.g. the penrose triangle [0]?

if so, how did it turn out? :)

I would love to hear how that went or see screenshots.

[0] https://en.wikipedia.org/wiki/Penrose_triangle

**Comment by MangoLion** [comment]
![Image](https://github.com/user-attachments/assets/ccb657d9-d8dc-45ca-81e9-bc6a8a0ed0d7)

**Comment by recursive-rat4** [comment]
[The wormhole of the University of Tübingen](https://www.spacetimetravel.org/wurmlochflug)

![](https://github.com/user-attachments/assets/283e3a0e-0727-409c-81bd-c4f771a02943)
