### ISSUE TITLE
How to use it in Colab

### ISSUE THREAD

**Issue by darkon12** [microsoft/TRELLIS#60]
Ok, there's probably a cleaner way to do this but I didn't find it so...
The first thing you have to do is completely remove Cuda/Cuda-toolkit as per:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#removing-cuda-toolkit
Then install cuda-toolkit 11.8 as per:
https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
Then install conda & clone and setup TRELLIS.
Finally modify app.py adding the line:
os.environ['ATTN_BACKEND'] = 'xformers'
right after 'import os' line.
And change the last line to:
demo.launch(share=True)
Notebook is here:
https://github.com/darkon12/TRELLIS-Colab
First two cells take forever and is not exactly lightning fast but it works (finally).

**Comment by realisticdreamer114514** [comment]
Works fine on free Colab T4 (12.6GB VRAM used) even tho the long setup time means I could only generate a single mesh before being timed out, cool job!

**Comment by realisticdreamer114514** [comment]
Found an issue of sorts on my 2nd run with the 1st cell, I started an issue in your repo, pls check & see if you would fix it, thx! https://github.com/darkon12/TRELLIS-Colab/issues/1

**Comment by jackel27** [comment]
Made a full working colab, Cloudflare or nGrok is in there also. Check it out:
[Kaiser-Trellis-Colab](https://github.com/jackel27/Trellis-Colab)

**Comment by darkon12** [comment]
Made a full working colab notebook a month ago.
Check it out:
https://github.com/darkon12/TRELLIS-Colab
;)

**Comment by jackel27** [comment]
I tried that, i think a week ago or .. some time. . But I remember it didn't work? Had dependency issues or something, I can't remember exactly. Actually
 Alot of people couldn't figure out the dependencies etc... or something when trying to get it working in their environment. I never found or witnessed a stable successful version.

Glad to share my trellis colab that works for me. Now off to bigger things with it.  👍

**Comment by darkon12** [comment]
>But I remember it didn't work?
No, It works great.
>Now off to bigger things with it. 👍
Yeah, just don't lie on other people's work  👍

**Comment by darkon12** [comment]
> I tried that, i think a week ago or .. some time. . But I remember it didn't work? Had dependency issues or something, I can't remember exactly. Actually Alot of people couldn't figure out the dependencies etc... or something when trying to get it working in their environment. I never found or witnessed a stable successful version.
> 
> Glad to share my trellis colab that works for me. Now off to bigger things with it. 👍
