### ISSUE TITLE
Hugging Face Demo Space is Broken

### ISSUE THREAD

**Issue by BrainSlugs83** [microsoft/TRELLIS#61]
Whenever I try to generate an image via the Hugging Face Demo Space (linked to by the paper when clicking "DEMO"), it just errors out, no specific error message other than "Error", and it doesn't matter what image you upload, it just always fails.

![Image](https://github.com/user-attachments/assets/b17d7139-032c-4705-a851-0545289d58eb)

The URL for the space is: https://huggingface.co/spaces/JeffreyXiang/TRELLIS
I believe this is an official demo supported by the project because clicking "DEMO" in the paper takes me there (and clicking code takes me here), so apologies if I got something wrong, but hopefully this is easy to fix. 🙂

**Comment by MangoLion** [comment]
I hosted the model on my pc in the meantime
https://justaaa.pages.dev

**Comment by JeffreyXiang** [comment]
I have just fixed it. Try it now!
