### ISSUE TITLE
Release of encoder models

### ISSUE THREAD

**Issue by philipbecker** [microsoft/TRELLIS#64]
Will you also be releasing the encoder models? This would enable use cases where one already has a 3D model (not generated by TRELLIS), but wants to modify parts of it using TRELLIS.

**Comment by Royalvice** [comment]
https://huggingface.co/JeffreyXiang/TRELLIS-image-large/blob/main/ckpts/slat_enc_swin8_B_64l8_fp16.safetensors
it seems the vae encoder of Structed Latents

**Comment by YuDeng** [comment]
The encoder part has been released. See https://github.com/microsoft/TRELLIS/blob/main/dataset_toolkits/extract_feature.py for how to transfer a 3D asset into SLAT.
