### ISSUE TITLE
Demo page showing models with no textures?

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/TRELLIS#67]
is this intentional?

![Image](https://github.com/user-attachments/assets/6b33679b-7ad7-4bdd-b948-67dbf92d4c1d)

the page crashed the first time I tried to load it, so maybe there's a buggy shader or something?

I'm on Chrome on a Win 11 ARM tablet, so maybe this has some GPU requirements it doesn't satisfy or something?

**Comment by MangoLion** [comment]
iirc small devices like phones have much lower browser texturepage size limit, so the model's 2048x2048 texture page might exceed that

**Comment by mindplay-dk** [comment]
right, this works fine on my laptop and workstation, so probably just a device limitation. let's just close this. ☺️
