### ISSUE TITLE
Running or Installing Trellis for non technical users

### ISSUE THREAD

**Issue by No1Idle** [microsoft/TRELLIS#69]
Hi,

my question is maybe stupid but I'm not very expert in programming/linux
I'm trying to use trellis and it seems great, Thank you!  I have the issue that the "preview" from the video (mp4) and the glb object i get are sometimes really different. I think it is due to the simplify value. I would like to try lower value of simplify (0.6 maybe?) but from the hugginface site I cannot do this..  I could try to install locally trellis but I'm not sure i can do this (not sure expert with linux) and in any case my gpu has only 12gb ram so not the 16 required. 

I have a doubt: does the App.py  file requires to install trellis locally or just the Gradio enviroment? Could I change just the App.py file to have a low simplify and run Trellis online?

Thanks in advance to anyone that can help me

**Comment by FishWoWater** [comment]
@No1Idle Hi, 
App.py DOES requires a from-scratch installation of trellis on your PC/server. BUT a simpler alternative you can try is to duplicate this space (on the right of the `Community` button):
https://huggingface.co/spaces/JeffreyXiang/TRELLIS/tree/main
edit its app.py and use huggingface platform to host your service

**Comment by No1Idle** [comment]
Thanks @FishWoWater,

it seems a great idea and surely easier than anything else i was thinking. Thanks a Lot!

**Comment by Lion320Dev** [comment]
Hello. 
I want to generate 3D asset from text prompt using Trellis AI model.
Can you let me know what is the best solution?
Thank you.

**Comment by FishWoWater** [comment]
There are a number of commercial 3D AI providers (web app version & API version), for example
https://hyper3d.ai/
https://www.tripo3d.ai/app/home

If you definitely want TRELLIS and don't want to deploy it by yourself
try on replicate, but it only supports image-to-3d and DOESN'T support text-to-3d
https://replicate.com/firtoz/trellis 


> Hello. I want to generate 3D asset from text prompt using Trellis AI model. Can you let me know what is the best solution? Thank you.
