### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by qiuxin610** [microsoft/TRELLIS#72]
window 11 
[SPARSE] Backend: spconv, Attention: flash_attn
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 3090" (24 GiB, sm_86, mempool enabled)
   Kernel cache:
     C:\Users\xin.qiu1\AppData\Local\NVIDIA\warp\Cache\1.5.0
d:\Miniconda\envs\trellis\lib\site-packages\gradio_client\utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: flash_attn
F:\work\python\TRELLIS\trellis\representations\mesh\flexicubes\flexicubes.py:22: UserWarning: expandable_segments not supported on this platform (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/cuda/CUDAAllocatorConfig.h:28.)
  self.dmc_table = torch.tensor(dmc_table, dtype=torch.long, device=device, requires_grad=False)
Using cache found in C:\Users\xin.qiu1/.cache\torch\hub\facebookresearch_dinov2_main
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "d:\Miniconda\envs\trellis\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
C:\Users\xin.qiu1/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
C:\Users\xin.qiu1/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
C:\Users\xin.qiu1/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
Running on local URL:  http://127.0.0.1:7860

 File "d:\Miniconda\envs\trellis\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 94, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA out of memory. Tried to allocate 964.03 GiB. GPU 0 has a total capacity of 24.00 GiB of which 16.77 GiB is free. Of the allocated memory 5.44 GiB is allocated by PyTorch, and 457.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
help

**Comment by jclarkk** [comment]
https://github.com/microsoft/TRELLIS/issues/6

**Comment by qiuxin610** [comment]
@jclarkk  ok tks
