### ISSUE TITLE
There is a floor beneath the output mesh

### ISSUE THREAD

**Issue by wangzhongliang** [microsoft/TRELLIS#76]
![Image](https://github.com/user-attachments/assets/1871cf9b-57b1-40b6-b004-4c61c254cafa)

The original image has no floor
After removing background, there is only one object in the center of image
But the output mesh contains a square floor beneath the object

Is there any way to remove the floor?
Any help is appreciated

Here is the original image: 
![Image](https://github.com/user-attachments/assets/b62ae083-2090-475f-9892-00aa84621f02)

**Comment by FishWoWater** [comment]
@wangzhongliang A simple solution:   try to generate many times, with option `randomize seed` ON until the floor disappear.

**Comment by wangzhongliang** [comment]
> [@wangzhongliang](https://github.com/wangzhongliang) A simple solution: try to generate many times, with option `randomize seed` ON until the floor disappear.

thx, I will try this

**Comment by wangzhongliang** [comment]
![Image](https://github.com/user-attachments/assets/bd80c79d-4678-4b0d-bd9a-007ec7a9dd66)
I load the exported ply into supersplat
and found out that the splats of the "floor" are transparent 
That is why they cannot be seen in rendered RGB  video

**Comment by wangzhongliang** [comment]
> I recommend switching to RMBG 2.0, it's much better than rembg and solves this issue since it generates the alpha channel more reliably.
> 
> You can see how I've done so here: [Link](https://github.com/jclarkk/TRELLIS/blob/main/trellis/pipelines/trellis_image_to_3d.py)
> 
> Have a look at the preprocess_image function.

thx jclarkk, I switched to RMGB 2.0(disable the original rmbg in the code)
And then the problem is solved
![Image](https://github.com/user-attachments/assets/2b0540b9-7ecb-476c-8c84-3f2f59cd4975)

**Comment by wangzhongliang** [comment]
> I recommend using a background remover yourself first so you can be sure that the image is cut out properly. The best model imo is inspyrenet https://huggingface.co/spaces/gokaygokay/Inspyrenet-Rembg

sorry MangoLion, I switched the rmbg to inspyrenet, but the problem is not solved
