### ISSUE TITLE
How to convert a 3D asset into Structured LATents (SLAT) ?

### ISSUE THREAD

**Issue by XiaokunSun** [microsoft/TRELLIS#81]
Hello, author! I am very interested in your work, especially the design of Structured LATents. I want to know how to convert a 3D asset (mesh、NeRF、3DGS) into Structured LATents? According to your paper, this process includes steps such as voxelization, 2D feature extraction, and encoding. Will you open source this part of the code?

Looking forward to your reply！

**Comment by YuDeng** [comment]
Converting a 3D asset into SLAT includes four steps:
1. Extract active voxels that intersect with object's surface.
2. Render multi-view images of the object, and extract Dino-v2 features of each image.
3. Back-project Dino-v2 features to the active voxels, and take average of the multiview features within each voxel.
4.  Compress the above voxelized features into SLAT via a shallow transformer encoder.

We plan to release all the code for reproduction, involving data preprocessing, training for SLAT encoder and decoder, as well as training for rectified flow transformers. Please stay tuned!

**Comment by XiaokunSun** [comment]
Thanks for your reply, looking forward to your update!

**Comment by melo513** [comment]
> Converting a 3D asset into SLAT includes four steps:
> 
> 1. Extract active voxels that intersect with object's surface.
> 2. Render multi-view images of the object, and extract Dino-v2 features of each image.
> 3. Back-project Dino-v2 features to the active voxels, and take average of the multiview features within each voxel.
> 4. Compress the above voxelized features into SLAT via a shallow transformer encoder.
> 
> We plan to release all the code for reproduction, involving data preprocessing, training for SLAT encoder and decoder, as well as training for rectified flow transformers. Please stay tuned!

about 4. step, how to convert the voxelied features into sparseTensor ?

**Comment by YuDeng** [comment]
> > Converting a 3D asset into SLAT includes four steps:
> > 
> > 1. Extract active voxels that intersect with object's surface.
> > 2. Render multi-view images of the object, and extract Dino-v2 features of each image.
> > 3. Back-project Dino-v2 features to the active voxels, and take average of the multiview features within each voxel.
> > 4. Compress the above voxelized features into SLAT via a shallow transformer encoder.
> > 
> > We plan to release all the code for reproduction, involving data preprocessing, training for SLAT encoder and decoder, as well as training for rectified flow transformers. Please stay tuned!
> 
> about 4. step, how to convert the voxelied features into sparseTensor ?

We just discard the inactive voxels and serialize the active ones as a 1-D sequence with their voxel indices as positional encodings, as described in Sec. 3.2 in our paper.

**Comment by FishWoWater** [comment]
In case anyone needs a single script for dataset processing 
``` shell 
set -e 
set -x 
# install requirements and depdendencies 
. ./dataset_toolkits/setup.sh

export DATASET_NAME=ObjaverseXL
export DATASET_SOURCE=sketchfab
export OUTPUT_DIR=datasets/ObjaverseXL_sketchfab
export RANK=0
export WORLD_SIZE=1600
export MAX_WORKERS=6

# initially build meta data of the specified dataset
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}
echo "Init building metadata done."

# download dataset
python dataset_toolkits/download.py ${DATASET_NAME} --output_dir ${OUTPUT_DIR} --world_size ${WORLD_SIZE}
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}
echo "Dataset Downloaded."

# render multi-view images with blender (e.g. 150 views)
python dataset_toolkits/render.py ${DATASET_NAME} --output_dir ${OUTPUT_DIR} --max_workers ${MAX_WORKERS}
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}

# voxelization (based on open3d)
python dataset_toolkits/voxelize.py ${DATASET_NAME} --output_dir ${OUTPUT_DIR}
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}

# extract DINOv2 features
python dataset_toolkits/extract_feature.py --output_dir ${OUTPUT_DIR}
# update meta data
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}

# extract SparseStructure Latents
python dataset_toolkits/encode_ss_latent.py --output_dir ${OUTPUT_DIR}
# update meta data
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}

# encode to SLATS
python dataset_toolkits/encode_latent.py --output_dir ${OUTPUT_DIR}
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR} 

# render condition images
python dataset_toolkits/render_cond.py ${DATASET_NAME} --output_dir ${OUTPUT_DIR}
python dataset_toolkits/build_metadata.py ${DATASET_NAME} --source ${DATASET_SOURCE} --output_dir ${OUTPUT_DIR}

```

**Comment by rururuw** [comment]
> Converting a 3D asset into SLAT includes four steps:
> 
> 1. Extract active voxels that intersect with object's surface.
> 2. Render multi-view images of the object, and extract Dino-v2 features of each image.
> 3. Back-project Dino-v2 features to the active voxels, and take average of the multiview features within each voxel.
> 4. Compress the above voxelized features into SLAT via a shallow transformer encoder.
> 
> We plan to release all the code for reproduction, involving data preprocessing, training for SLAT encoder and decoder, as well as training for rectified flow transformers. Please stay tuned!

May I ask where is the code for step 2 and 3? In the example [trellis_text_to_3d.py](https://github.com/microsoft/TRELLIS/blob/main/trellis/pipelines/trellis_text_to_3d.py) (`run_variant()`), it seems only the voxels with shape (L, 4) and condition are used to sample SLATs. I could not find where the dino-v2 features are computed. Can someone plz tell me if I missed anything?
