### ISSUE TITLE
Pink models after the latest update

### ISSUE THREAD

**Issue by IgorAherne** [microsoft/TRELLIS#83]
Hello people, getting this kind of render:
![Image](https://github.com/user-attachments/assets/b06364d4-4d6e-49d9-9fe6-db195b471d08)

Can someone point in which direction to search, what module is responsible for coloring things?
The mesh also has inverted polygons

It was working fine a week ago, possibly something due to the Mip-Splatting?

**Comment by IgorAherne** [comment]
I noticed that when Trellis completes generation the `sample_gs.mp4` also shows this castle that looks pink and is flickering.
Possibly this info might be helpful:
![Image](https://github.com/user-attachments/assets/af401ae9-3c67-4122-bd2b-5de5cd9025f0)

Here are the 3 videos, sample_gs.mp4 (flickers), sample_mesh.mp4 (normals fine), sample_rf (colors fine), 
https://github.com/user-attachments/assets/1bae1e12-7349-4aa3-8c29-f15779eef9e9
https://github.com/user-attachments/assets/ae4a86ef-de1c-435e-a307-e82808bba0dc
https://github.com/user-attachments/assets/dc766d76-a6a0-4f83-808f-bd6c48b0629d

**Comment by cjjkoko** [comment]
Z-Fighting，try export glb

**Comment by IgorAherne** [comment]
Nope, GLB has the same weird problem, inverted polygons and this pinkish texture

**Comment by IgorAherne** [comment]
This was due to incorrect installation of the `mip-splatting` repository, and its dependency `diff_gaussian_rasterization`. 
I installed it from a another location. Once I installed the stuff from the submodules of the Trellis itself, the pink issue was resolved.
