### ISSUE TITLE
Questions on visual feature aggregation

### ISSUE THREAD

**Issue by c1enyang** [microsoft/TRELLIS#90]
> Converting a 3D asset into SLAT includes four steps:
> 1. Extract active voxels that intersect with object's surface.
> 2. Render multi-view images of the object, and extract Dino-v2 features of each image.
> 3. Back-project Dino-v2 features to the active voxels, and take average of the multiview features within each voxel.
> 4.  Compress the above voxelized features into SLAT via a shallow transformer encoder.
> 
> We plan to release all the code for reproduction, involving data preprocessing, training for SLAT encoder and decoder, as well as training for rectified flow transformers. Please stay tuned! 

 _Originally posted by @YuDeng in [#81](https://github.com/microsoft/TRELLIS/issues/81#issuecomment-2561562608)_

Thanks for the great work! I am trying to implement the above four steps to convert a 3D asset into SLAT and meet some problems: 
>1. In step 2, which Dino-v2 features are used? Are they the same as the image condition feature but remove clstokens and regtokens? If this is right, the spatial resolution of the Dino-v2 feature is 37*37. https://github.com/microsoft/TRELLIS/blob/f094d9f20ee2bc2e100ecce4d3ea7ea5119d7e21/trellis/pipelines/trellis_image_to_3d.py#L145
>2. In step 3, we can project an active voxel to each view (a total of 150 views) and get the image feature. Then, we can average the 150 image features. However, this way doesn't consider occlusion issues. Do you handle the occlusion issues in projection?
>3. In step 4, the shallow transformer encoder is https://huggingface.co/JeffreyXiang/TRELLIS-image-large/blob/main/ckpts/slat_enc_swin8_B_64l8_fp16.safetensors ?

Looking forward to your help.

**Comment by YuDeng** [comment]
@JeffreyXiang can help with a more detailed explanation.

**Comment by JeffreyXiang** [comment]
Hi, we just released dataset toolkits which contain code for visual feature aggregation. See [dataset_toolkits/extract_feature.py](https://github.com/microsoft/TRELLIS/blob/main/dataset_toolkits/extract_feature.py) for more details.

**Comment by c1enyang** [comment]
Thank you for the information!
